version: '3.8'
name: principal
services:
  local:
    container_name: local_server
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=libertybank
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./src/main/resources/sql/scripts.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8002
    ports:
      - "8002:8002"
    volumes:
      - ./server_config/servers.json:/pgadmin4/servers.json
volumes:
  db-data: