spring:
  datasource:
    url: jdbc:postgresql://http://localhost:5432/libertybank
    driverClassName: org.postgresql.Driver
    username: postgres
    password: iemf12345
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true